articles = [
    ("blog-huile-romarin.html", "Huile de Romarin : Pourquoi Elle Fait Pousser les Cheveux | Blog MÎJAH", "Ingrédients naturels", "Huile de Romarin :\nPourquoi Elle Fait Pousser les Cheveux",
     "Découvrez la science derrière l'huile de romarin et comment l'utiliser pour stimuler la pousse des cheveux naturellement.",
     "huile romarin cheveux, romarin pousse cheveux, bienfaits romarin capillaire",
     "photosAndvideos/Mijah%20hair%20growth%20oil.png", "2024-03-10",
     "blog-chute-cheveux.html,Chute,Stopper la chute des cheveux|blog-routine-crepus.html,Routine,Routine complète cheveux crépus",
     "product-rosemary.html", "Huile de Croissance Rosemary MÎJAH", "12.80", "photosAndvideos/Mijah hair growth oil.png"),
    ("blog-beurre-mangue.html", "Beurre de Mangue pour Cheveux Bouclés : Bienfaits & Utilisation | Blog MÎJAH", "Hydratation", "Beurre de Mangue :\nL'Essentiel pour les Cheveux Bouclés",
     "Tout savoir sur le beurre de mangue pour les cheveux bouclés : bienfaits, application et pourquoi c'est indispensable.",
     "beurre de mangue cheveux, hydratation cheveux afro, définir boucles naturellement",
     "photosAndvideos/Mango%20Hair%20Butter.png", "2024-03-15",
     "blog-routine-crepus.html,Routine,Routine complète cheveux crépus|blog-erreurs-cheveux-afro.html,Conseils,5 erreurs qui abîment les cheveux Afro",
     "product-mango.html", "Beurre de Mangue MÎJAH", "19.90", "photosAndvideos/Mango Hair Butter.png"),
    ("blog-erreurs-cheveux-afro.html", "5 Erreurs qui Abîment les Cheveux Afro | Blog MÎJAH", "Conseils", "5 Erreurs qui Abîment\nles Cheveux Afro",
     "Les 5 erreurs les plus courantes avec les cheveux afro et bouclés, et les solutions simples pour des cheveux sains.",
     "erreurs cheveux afro, comment prendre soin cheveux crépus, cheveux abimés solutions",
     "photosAndvideos/Mijah%20Black%20girls%20trio.jpg", "2024-03-20",
     "blog-chute-cheveux.html,Chute,Stopper la chute des cheveux|blog-beurre-mangue.html,Hydratation,Beurre de Mangue : l'essentiel",
     "collection.html", "La Collection MÎJAH Complète", "", "photosAndvideos/Cleint Mijah Trio.jpg"),
]

